### ISSUE TITLE
Trying to build on ubuntu, no build.sh file

### ISSUE THREAD

**Issue by fstltna** [Maxwolf/OregonTrail#1]
I checked it out with the --recursive option, but I still don't see a build.sh script...

**Comment by fstltna** [comment]
Anyone see this? Been almost a year :(

**Comment by connormcdermid** [comment]
Cloned on Arch Linux, still no build.sh file...

**Comment by gliggy** [comment]
I ran into the same problem, seems like it was deleted in a commit. The latest commit with build.sh in it is this one: [https://github.com/Maxwolf/OregonTrail/tree/ae065cdc9b3fbb82cd85d58226741cf39543a420](https://github.com/Maxwolf/OregonTrail/tree/ae065cdc9b3fbb82cd85d58226741cf39543a420)
